
package com.runchain.exercise.admin.web.venue.wc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VenueServerService", targetNamespace = "http://service.venue.yanhl.net/", wsdlLocation = "http://118.126.4.171:9998/axis.exercise/venue?wsdl")
public class VenueServerService
    extends Service
{

    private final static URL VENUESERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.runchain.exercise.admin.web.venue.wc.VenueServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.runchain.exercise.admin.web.venue.wc.VenueServerService.class.getResource(".");
            url = new URL(baseUrl, "http://118.126.4.171:9998/axis.exercise/venue?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://118.126.4.171:9998/axis.exercise/venue?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VENUESERVERSERVICE_WSDL_LOCATION = url;
    }

    public VenueServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VenueServerService() {
        super(VENUESERVERSERVICE_WSDL_LOCATION, new QName("http://service.venue.yanhl.net/", "VenueServerService"));
    }

    /**
     * 
     * @return
     *     returns VenueServer
     */
    @WebEndpoint(name = "VenueServerPort")
    public VenueServer getVenueServerPort() {
        return super.getPort(new QName("http://service.venue.yanhl.net/", "VenueServerPort"), VenueServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VenueServer
     */
    @WebEndpoint(name = "VenueServerPort")
    public VenueServer getVenueServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.venue.yanhl.net/", "VenueServerPort"), VenueServer.class, features);
    }

}
